enum EarningActions {
  EARNING_ADD = "EARNING_ADD",
  EARNING_DELETE = "EARNING_DELETE",
  EARNING_UPDATE = "EARNING_UPDATE",
  EARNING_SELECT_ACTIVE = "EARNING_SELECT_ACTIVE",
  EARNING_CLEAN_ACTIVE = "EARNING_CLEAN_ACTIVE",
}

export default EarningActions;
