enum EarningActions {
  EARNING_ADD = "EARNING_ADD",
  EARNING_DELETE_ACTIVE = "EARNING_DELETE_ACTIVE",
  EARNING_UPDATE_ACTIVE = "EARNING_UPDATE_ACTIVE",
  EARNING_SELECT_ACTIVE = "EARNING_SELECT_ACTIVE",
  EARNING_CLEAN_ACTIVE = "EARNING_CLEAN_ACTIVE",
}

export default EarningActions;
