enum ExpenseActions {
  EXPENSE_ADD = "EXPENSE_ADD",
  EXPENSE_DELETE = "EXPENSE_DELETE",
  EXPENSE_UPDATE = "EXPENSE_UPDATE",
  EXPENSE_SELECT_ACTIVE = "EXPENSE_SELECT_ACTIVE",
  EXPENSE_CLEAN_ACTIVE = "EXPENSE_CLEAN_ACTIVE",
}

export default ExpenseActions;
