enum ExpenseActions {
  EXPENSE_ADD = "EXPENSE_ADD",
  EXPENSE_DELETE_ACTIVE = "EXPENSE_DELETE_ACTIVE",
  EXPENSE_UPDATE_ACTIVE = "EXPENSE_UPDATE_ACTIVE",
  EXPENSE_SELECT_ACTIVE = "EXPENSE_SELECT_ACTIVE",
  EXPENSE_CLEAN_ACTIVE = "EXPENSE_CLEAN_ACTIVE",
}

export default ExpenseActions;
