enum SavingActions {
  SAVING_ADD = "SAVING_ADD",
  SAVING_DELETE = "SAVING_DELETE",
  SAVING_UPDATE = "SAVING_UPDATE",
  SAVING_SELECT_ACTIVE = "SAVING_SELECT_ACTIVE",
  SAVING_CLEAN_ACTIVE = "SAVING_CLEAN_ACTIVE",
}

export default SavingActions;
