enum SavingActions {
  SAVING_ADD = "SAVING_ADD",
  SAVING_DELETE_ACTIVE = "SAVING_DELETE_ACTIVE",
  SAVING_UPDATE_ACTIVE = "SAVING_UPDATE_ACTIVE",
  SAVING_SELECT_ACTIVE = "SAVING_SELECT_ACTIVE",
  SAVING_CLEAN_ACTIVE = "SAVING_CLEAN_ACTIVE",
}

export default SavingActions;
