enum PaymentActions {
  PAYMENT_ADD = "PAYMENT_ADD",
  PAYMENTS_LOADED = "PAYMENTS_LOADED",
  PAYMENT_DELETE_ACTIVE = "PAYMENT_DELETE_ACTIVE",
  PAYMENT_UPDATE_ACTIVE = "PAYMENT_UPDATE_ACTIVE",
  PAYMENT_SELECT_ACTIVE = "PAYMENT_SELECT_ACTIVE",
  PAYMENT_CLEAN_ACTIVE = "PAYMENT_CLEAN_ACTIVE",
}

export default PaymentActions;
