enum DebtActions {
  DEBT_ADD = "DEBT_ADD",
  DEBT_DELETE_ACTIVE = "DEBT_DELETE_ACTIVE",
  DEBT_UPDATE_ACTIVE = "DEBT_UPDATE_ACTIVE",
  DEBT_SELECT_ACTIVE = "DEBT_SELECT_ACTIVE",
  DEBT_CLEAN_ACTIVE = "DEBT_CLEAN_ACTIVE",
}

export default DebtActions;
