enum DebtActions {
  DEBT_ADD = "DEBT_ADD",
  DEBT_DELETE = "DEBT_DELETE",
  DEBT_UPDATE_ACTIVE = "DEBT_UPDATE_ACTIVE",
  DEBT_SELECT_ACTIVE = "DEBT_SELECT_ACTIVE",
  DEBT_CLEAN_ACTIVE = "DEBT_CLEAN_ACTIVE",
  DEBT_UPDATE_PAYMENTS = "DEBT_UPDATE_PAYMENTS",
}

export default DebtActions;
